#!/usr/bin/python3
"""Module that factorizes as many numbers as possible
 into a product of two smaller numbers."""
import sys


def factorize(value):
    """Factorizes an integer greater than 1 and prints the factorization."""
    i = 2

    if value < 2:
        return

    print("{}=".format(value), end="")
    while value % i:
        i += 1
    print("{}*{}".format(i, int(value / i)))


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    print("where <file> is a file containing natural numbers to factorize.")
    sys.exit(1)

try:
    with open(sys.argv[1]) as file:
        for line in file:
            value = int(line.strip())
            factorize(value)
except FileNotFoundError:
    print("File not found: {}".format(sys.argv[1]))
except ValueError:
    print("Invalid file format: {}".format(sys.argv[1]))
