#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
    Usage: factors <file>
        where <file> is a file containing natural numbers to factor.
        One number per line
        You can assume that all lines will be valid natural numbers\
                greater than 1
        You can assume that there will be no empty line, and no space\
                before and after the valid number
        The file will always end with a new line
    Output format: n=p*q
        one factorization per line
        p and q don’t have to be prime numbers
        See example
    You can work on the numbers of the file in the order of your choice
    Your program should run without any dependency: You will not be able\
            to install anything on the machine we will run your program on
    Time limit: Your program will be killed after 5 seconds\
            if it hasn’t finished
    Push all your scripts, source code, etc… to your repository
"""
import sys


def factorize():
    """
    Function to read a file, factorize numbers, and print the factorization.
    """
    try:
        file_name = sys.argv[1]
        with open(file_name) as file:
            for line in file:
                number = int(line.strip())
                factors = []
                i = 2
                while i * i <= number:
                    if number % i:
                        i += 1
                    else:
                        factors.append(i)
                        number //= i
                if number > 1:
                    factors.append(number)
                print("{}={}".format(line.strip(), "*".join(map(str, factors))))
    except (IndexError, FileNotFoundError):
        pass


# Autostart the factorization process
factorize()
